default:
	javac -cp .:/usr/share/java/junit4.jar cpsc2150/connectX/*.java

test:
	java -cp .:/usr/share/java/junit4.jar org.junit.runner.JUnitCore cpsc2150.connectX.TestIGameBoard

run:
	java cpsc2150.connectX.Connect4Game
